#!/bin/sh

MKPM_BINARY=https://example.com

alias download="$(curl --version >/dev/null 2>&1 && echo curl -Lo || echo wget -O)"

_project_root() {
    _ROOT=$1
    if [ "$_ROOT" = "" ]; then
        _ROOT=$(pwd)
    fi
    if [ -f "$_ROOT/mkpm.yml" ]; then
        echo $_ROOT
        return
    fi
    _PARENT=$(echo $_ROOT | sed 's|\/[^\/]\+$||g')
    if ([ "$_PARENT" = "" ] || [ "$_PARENT" = "/" ]); then
        echo "/"
        return
    fi
    echo $(_project_root $_PARENT)
    return
}
export PROJECT_ROOT="$(_project_root)"
export _MKPM_BIN="$PROJECT_ROOT/.mkpm/mkpm/.bin"

if [ -f "$PROJECT_ROOT/mkpm.sh" ]; then
    mkdir -p "$_MKPM_BIN"
    if [ ! -f "$_MKPM_BIN/mkpm" ] || [ "$PROJECT_ROOT/mkpm.sh" -nt "$_MKPM_BIN/mkpm" ]; then
        export _MKPM_RESET_CACHE=1
        cp "$PROJECT_ROOT/mkpm.sh" "$_MKPM_BIN/mkpm"
    fi
    chmod +x "$_MKPM_BIN/mkpm"
elif [ ! -f "$_MKPM_BIN/mkpm" ]; then
    mkdir -p "$_MKPM_BIN"
    download "$_MKPM_BIN/mkpm" "$MKPM_BINARY" >/dev/null
    chmod +x "$_MKPM_BIN/mkpm"
fi

exec "$_MKPM_BIN/mkpm" "$@"
