#!/bin/sh

MKPM_BINARY=https://example.com
alias download="$(curl --version >/dev/null 2>&1 && echo curl -Lo || echo wget -O)"
_is_ci() {
    for v in "JENKINS_URL TRAVIS CIRCLECI GITHUB_ACTIONS GITLAB_CI TF_BUILD BITBUCKET_PIPELINE_UUID TEAMCITY_VERSION"; do
        if [ "$v" != "" ] && [ "$v" != "0" ] && [ "$(echo $v | tr '[:upper:]' '[:lower:]')" != "false" ]; then
            return 1
        fi
    done
    return
}
_CI="$(_is_ci && echo 1 || true)"
_CWD="$(pwd)"
if [ "$_CI" = "" ]; then
    export NOCOLOR='\e[0m'
    export RED='\e[0;31m'
    export YELLOW='\e[0;33m'
fi
_error() {
    echo "${RED}MKPM [E]:${NOCOLOR} $@" 1>&2
}
_debug() {
    [ "$MKPM_DEBUG" = "1" ] && echo "${YELLOW}MKPM [D]:${NOCOLOR} $@" || true
}
_project_root() {
    _ROOT=$1
    if [ "$_ROOT" = "" ]; then
        _ROOT="$(pwd)"
    fi
    if [ -f "$_ROOT/mkpm.json" ]; then
        echo $_ROOT
        return
    fi
    _PARENT=$(echo $_ROOT | sed 's|\/[^\/]\+$||g')
    if ([ "$_PARENT" = "" ] || [ "$_PARENT" = "/" ]); then
        echo "/"
        return
    fi
    echo $(_project_root $_PARENT)
    return
}
_restore_from_cache() {
    mkdir -p "$MKPM"
    cd "$MKPM"
    tar -xzf "$_MKPM_ROOT/cache.tar.gz"
    cd "$_CWD"
    _debug restored cache
}
export PROJECT_ROOT="$(_project_root)"
if [ "$PROJECT_ROOT" = "/" ]; then
    _error "not an mkpm project" && exit 1
fi
export _MKPM_ROOT="$PROJECT_ROOT/.mkpm"
export MKPM="$_MKPM_ROOT/mkpm"
export _MKPM_BIN="$MKPM/.bin"
if [ -f "$PROJECT_ROOT/mkpm.sh" ]; then
    mkdir -p "$_MKPM_BIN"
    if [ ! -f "$_MKPM_BIN/mkpm" ]; then
        if [ -f "$_MKPM_ROOT/cache.tar.gz" ]; then
            _restore_from_cache
        else
            cp "$PROJECT_ROOT/mkpm.sh" "$_MKPM_BIN/mkpm"
            _debug downloaded mkpm.sh
        fi
    elif [ "$PROJECT_ROOT/mkpm.sh" -nt "$_MKPM_BIN/mkpm" ]; then
        export _MKPM_RESET_CACHE=1
        cp "$PROJECT_ROOT/mkpm.sh" "$_MKPM_BIN/mkpm"
    fi
    chmod +x "$_MKPM_BIN/mkpm"
elif [ ! -f "$_MKPM_BIN/mkpm" ]; then
    mkdir -p "$_MKPM_BIN"
    if [ -f "$_MKPM_ROOT/cache.tar.gz" ]; then
        _restore_from_cache
    else
        download "$_MKPM_BIN/mkpm" "$MKPM_BINARY" >/dev/null
        _debug downloaded mkpm.sh
    fi
    chmod +x "$_MKPM_BIN/mkpm"
fi
exec "$_MKPM_BIN/mkpm" "$@"
